time-series:
  uri: ""
  zone: ""
uaa:
  uri: ""
  client: ""
  secret: ""
  username: ""
  password: ""
  token: ""
csv:
  delimiter: ";"
  concatchar: "_"
  timestamp: "%m/%d/%Y %I:%M:%S %p"
  packetsize: 500
  metername: -1
  indexes: 
    equipment: 1
    tag: 2
    timestamp: 3
    value: 4